name: Deploy

on:
  push:
    branches: [main]

  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build with vite
        run: |
          bun run build

      - name: Deploy to Bunny.net
        uses: ayeressian/bunnycdn-storage-deploy@96e259ff251df6d45f74e913c05ba870f8e061a7
        with:
          source: "docs/.vitepress/dist"
          storageZoneName: "${{ secrets.STORAGE_NAME }}"
          storagePassword: "${{ secrets.STORAGE_PASSWORD }}"
          accessKey: "${{ secrets.CDN_ACCESS_KEY }}"
          pullZoneId: "${{ secrets.PULL_ZONE_ID }}"
          upload: "true"
          remove: "true"
          purgePullZone: "true"
